spring.application.name=bank-management
spring.datasource.url=jdbc:postgresql://localhost:5434/bank_cards
spring.datasource.username=bank_user
spring.datasource.password=bank_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml